let Type = '<select name="type"><option value=""></option><option class="type" value="hk">Housekeeping</option><option class="type" value="cw">Civil Works</option></select>'

let Area = '<select name="area"><option value=""></option><option class="area" value="entrance">entrance</option><option class="area" value="selling">selling area</option><option class="area" value="counter">counter area</option><option class="area" value="dining">dining area</option><option class="area" value="backroom">backroom area</option><option class="area" value="restroom">restroom</option><option class="area" value="second_floor">second Floor</option><option class="area" value="exterior">exterior</option></select>';

let Finding = '<select name="finding"><option value=""></option><option class="finding" value="dirty">Dirty</option><option class="finding" value="overcrowded">Overcrowded stocks</option><option class="finding" value="stagnant">Stagnant water</option><option class="finding" value="gap">Gap</option><option class="finding" value="hole">Hole</option><option class="finding" value="damaged">Damaged</option><option class="finding" value="uncovered">Uncovered</option><option class="finding" value="open">Always Open</option><option class="finding" value="doors">Misaligned doors</option></select>';

let Origin = '<select name="origin"><option value=""></option><option class="origin" value="drainage">drainage</option><option class="origin" value="tiles">tiles</option><option class="origin" value="window_1">window</option><option class="origin" value="pipe">around the pipe</option></select>';

let Place = '<select name="place"><option value=""></option><option value="sink">under the sink</option><option class="origin" value="cabinet_1">under the cabinet</option><option class="origin" value="cabinet_2">above the cabinet</option><option class="origin" value="gondolas">under the gondolas</option><option class="origin" value="food_island_1">under the food island</option><option class="origin" value="food_island_2">above the food island</option><option class="origin" value="tank_1">under the water tank</option><option class="origin" value="tank_2">above the water tank</option><option class="origin" value="postmix_1">behind the postmix</option><option class="origin" value="postmix_2">under the postmix</option><option class="origin" value="postmix_3">above the postmix</option><option class="origin" value="table">under the table</option><option class="origin" value="office">in the office</option><option class="origin" value="slurpee_1">behind the slurpee</option><option class="origin" value="slurpee_2">under the slurpee</option><option class="origin" value="slurpee_3">above the slurpee</option><option class="origin" value="gulp_1">behind the gulp machine</option><option class="origin" value="gulp_2">under the gulp machine</option><option class="origin" value="gulp_3">above the gulp machine</option><option class="origin" value="atm_1">behind the atm</option><option class="origin" value="atm_2">under the atm</option><option class="origin" value="atm_3">above the atm</option><option class="origin" value="wall">on the wall</option><option class="origin" value="ceiling_1">in the ceiling</option><option class="origin" value="ceiling_2">inside the ceiling</option><option class="origin" value="panel_board">above the panel board</option><option class="origin" value="baseboard">in the baseboard</option><option class="origin" value="door_1">on the door</option><option class="origin" value="door_2">under the door</option><option class="origin" value="window_2">near the window</option><option class="origin" value="aircon_1">under the aircon</option><option class="origin" value="aircon_2">above the aircon</option><option class="origin" value="showcase_1">under the open showcase</option><option class="origin" value="showcase_2">above the open showcase</option><option class="origin" value="outside">outside the store</option></select>';
