let data = {
	"Type":[
		"Housekeeping",
		"Civil Works"
	],
	"Area": [
		"Entrance",
		"Selling Area",
		"Counter Area",
		"Dining Area",
		"Backlot Area",
		"Restroom",
		"Second Floor",
		"Exterior"
	],
	"Finding": [
		"Dirty",
		"Trash",
		"Overcrowded stocks",
		"Unused equipments",
		"Stagnant water",
		"Gap",
		"Gap on the wall",
		"Gap around the pipe",
		"Gap around the hose",
		"Gap around the electrical pipe",
		"Gap under the door",
		"Gap on the door",
		"Gap on the baseboard",
		"Hole",
		"Hole in the ceiling",
		"Hole in the wall",
		"Damaged tiles",
		"Damaged wall",
		"Damaged ceiling",
		"Misaligned doors",
		"Uncovered drainage",
		"Uncovered pipe",
		"Uncovered wall",
		"Uncovered ceiling",
		"Window always open",
		"Door always open"
	],
	"Additional": [
		"under",
		"above",
		"behind",
		"inside",
		"of",
		"on",
		"near",
		"in",
		"at",
		"through"
	],
	"Specifics": [
		"the cabinet",
		"the handwash",
		"the mop sink",
		"the water tank",
		"the walk in",
		"the freezer",
		"the chiller",
		"the walk in freezer",
		"the walk in chiller",
		"the open showcase",
		"the postmix",
		"the atm",
		"the BiB",
		"the baseboard",
		"the gondolas",
		"the food island",
		"the office",
		"the panel board",
		"the slurpee",
		"the gulp machine",
		"the ceiling",
		"the wall",
		"the window",
		"the stairs",
		"the storage",
		"the fire exit",
		"the ilt",
		"the entrance",
		"on the glasswall"
	]
}
